Task9
jwei176/kintone_dojo pull request #10
Opened 2023-06-22 06:55 UTC by jwei176

お疲れ様です！

いつもレビューありがとうございます。
タスク９のRESTAPI２の課題です。

レビューお願いいたします！🙇‍♂️

2023-06-26 08:27 UTC, s-iwakawa requested changes

2023-06-26 08:27 UTC, s-iwakawa commented on task9.js
一度watchdogを通してプルリクしてください！
コメント行で warning が出ています！

2023-06-26 08:27 UTC, s-iwakawa commented on task9.js
> +  kintone.events.on('app.record.create.submit', async (event) => {
今回のコードでは、`create.submit`しか記述されていませんが、
実際重複チェックは編集画面でもする必要があります。

編集画面でも対応できるように変更してください！

2023-06-26 09:48 UTC, jwei176 commented
レビューありがとうございます。

>一度watchdogを通してプルリクしてください！

大変失礼しました。😰
この課題の訂正と中間はwatchdogの審査を通しているはずです。
本堂にすみませんでした。🙇‍♂️

>今回のコードでは、create.submitしか記述されていませんが、
実際重複チェックは編集画面でもする必要があります。

edit.submitを使って編集画面でも対応できるように変更してみました。
お手数ですが、レビューお願い致します！🙇‍♂️

2023-06-27 00:26 UTC, s-iwakawa requested changes

2023-06-27 00:26 UTC, s-iwakawa commented on task9.js
> +    return event;
edit.submitの追加ナイスです。

しかし、この場合を考えてみてください。
レコード新規作成で `20230627-GR-1`を作成した。
そのレコードの編集画面を開いて、操作せずにそのまま保存。
すると、他のレコードとは重複していないのにアラートが出ます。

なぜでしょう！
この状態では、34行目のREST APIで「今開いているレコード」自体も取得しているためです。

これを解決するように修正してください。

もし解決するアイデアを思いつけなければ、相談してください。

2023-06-27 01:57 UTC, jwei176 commented on task9.js
> +    return event;
お疲れ様です！

REST APIで「今開いているレコード」自体を取得したくないので、クエリを使おうと思いました。
ですが、
```
const ID = kintone.app.getId();
const record_ID = kintone.app.record.getId();
const query = "レコード番号 != record_ID";
const params = {
  app: ID,
  'query': query,
};
```
クエリの書き方を参考できるサイトが見つからなかった、質問させていただきました。
`const query = `の書き方だけ教えていただけると幸いです！

2023-06-27 02:16 UTC, jwei176 commented
お疲れ様です！

クエリを適当に書いたら上手く行ったようなので、修正したコードをプルリクしました。
レビューのほどお願い致します！🙇‍♂️

2023-06-27 05:07 UTC, s-iwakawa reviewed
レビューOKです。

さらに言うとすれば、create, edit の両方一緒にしてしまって、中で条件分岐させると

2023-06-27 05:07 UTC, s-iwakawa approved these changes

2023-06-27 05:23 UTC, merged

2023-06-27 05:26 UTC, jwei176 commented
お疲れ様です！

レビューありがとうございました！🙇‍♂️