mid
jwei176/kintone_dojo pull request #12
Opened 2023-06-26 09:09 UTC by jwei176

お疲れ様です。
お手数ですが、レビューのほどよろしくお願いいたします！🙇‍♂️

2023-06-27 05:32 UTC, s-iwakawa requested changes

2023-06-27 05:32 UTC, s-iwakawa commented on mid_task/mid.html
> +      const cell1 = row.insertCell();
```
row.insertCell().textContent = resp.data[ele].day.value;
row.insertCell().textContent = resp.data[ele].category.value;
```
変数に格納せずに上記のような書き方でも問題ないです。
むしろ、変数を作った後に使ってないなら、その場で処理を書いちゃう方がいいです。

2023-06-27 05:32 UTC, s-iwakawa commented on mid_task/mid.html
> +      }
else は55行目と全く同じ値を再代入しているだけなので必要なし

2023-06-27 05:32 UTC, s-iwakawa commented on mid_task/mid.html
> +    $("td:contains('企業情報')").css('background-color', '#00b7eb');
ここでstyle をいじるなら、
cssにあらかじめそれぞれのクラスを準備しておいて、
54行目で扱っているcategoryのtdの要素に`elm.classList.add('className')`でクラスを追加するとjsに余計な操作が必要なく、jquery も必要なくなるかと思います。

そうすると条件分岐が必要になりますが、三項演算子を使ってみてください。

jquery もいいんですが、自分は使わない派です。

2023-06-27 05:32 UTC, s-iwakawa commented on mid_task/mid.html
めちゃくちゃOKなのですが、jqueryを無くした形に書き換えてみてください。
ジュンくんは手直し少なめというか、理解度高そうなので色々試して欲しい気持ちがあります笑

2023-06-28 00:52 UTC, jwei176 commented
お疲れ様です！

>54行目で扱っているcategoryのtdの要素にelm.classList.add('className')でクラスを追加するとjsに余計な操作が必要なく、jquery も必要なくなるかと思います。

ご指摘ありがとうございます！
`elm.classList.add('className')`を使ってクラスの追加をしてから、cssで背景の色を変えてみました！
お手数ですが、ご確認のほどよろしくお願いいたします。🙇‍♂️

2023-06-28 00:56 UTC, s-iwakawa approved these changes
ナイスです！
お疲れ様でした！

2023-06-28 01:00 UTC, jwei176 commented
kintone dojo課題のレビューいつもありがとうございました！
研修課題の方もこれからよろしくお願いいたします。🙇‍♂️

2023-06-28 01:00 UTC, merged