task4
jwei176/kintone_dojo pull request #5
Opened 2023-06-16 05:09 UTC by jwei176

いつもお世話になっております。

お忙しいところ恐縮ですが、レビューのほどよろしくお願いいたします！🙇‍♂️

2023-06-21 01:06 UTC, s-iwakawa requested changes
全体的な修正になりますが、シンプルなコードを目指して修正してみてください！

2023-06-21 01:06 UTC, s-iwakawa commented on Day4/task4-1.html
> +    const total = document.getElementById('price').textContent;
const はどこかで値が再代入されたりすることを防いでくれる役割はありますが、今回の課題の場合は、逆に処理・記述が複雑になるので、letを使用するとよいです。
`let total = 3900;`

2023-06-21 01:06 UTC, s-iwakawa commented on Day4/task4-1.html
> +        document.getElementById('price').textContent = Number(total) + (Number(val1) * 5);
ここでは、代入演算子の +=  や -= を使ってみてください！
(78, 80, 82, 84, 91, 93, 95, 97 行目も同様)

2023-06-21 01:06 UTC, s-iwakawa commented on Day4/task4-1.html
> +      }
ifの波括弧内で記述したすべての処理に `document.getElementById('price').textContent = 値`が行われているので、onclickの中だけど、ifの外に値を代入する処理を一回で十分です。

2023-06-21 01:06 UTC, s-iwakawa commented on Day4/task4-2.html
> +    const val1 = document.getElementsByClassName('chk')[0].value;
なるべくval や arg, num のような何の数字かわからない変数名はつけない方が良いです。
今回でいうと、
73行目で
`const checkbox = document.getElementsByClassName('chk');`
それ以降は、`checkbox[<0, 1 のような取り出したい数字>]`で指定してあげるのでOK。

2023-06-21 01:06 UTC, s-iwakawa commented on Day4/task4-2.html
> +      }
4-1の課題と同様に、ifの処理が共通している部分は外に書いてしまうのが良いです。
間違いだったり、変更があると書き直しにも時間がかかりますし、修正ミスも増えます。

2023-06-21 01:06 UTC, s-iwakawa commented on Day4/task4-2.html
> +        document.getElementById('price').textContent = Number(arr[0]) + Number(total);
4-1同様に total としている部分に let を使うことで再代入が可能になります。
そうするとif文の条件式には
`if (checkbox1.checked) `
のみでOKになるようなシンプルな記述になるので一度全体を見直してみてください！

補足で、
.checked には true or false が元々入っているので、わざわざ === で左右の比較を行う必要がなく、そのまま使えます

2023-06-21 06:48 UTC, jwei176 commented
コードを編集いたしました！
task4-2.htmlは大幅に書き換えてので、お手数ですが、レビューお願いいたします！

よろしくお願いいたします！🙇‍♂️

2023-06-23 00:33 UTC, s-iwakawa reviewed
動きはOKです！

両方のファイルで共通ですが、インデントは合わせましょう。
微修正したら自信でマージOKです！

レビュー遅れてすみません！

2023-06-23 00:33 UTC, s-iwakawa commented on Day4/task4-2.html
> +      };
ここで、chk1_opt を使わない方法をとると、
```
if (chkbox[0].checked) {
  total += Number(chkbox[0].value) * Number(select[0].value);
}
```
これをchkbox[1]の分を用意して、最後に`... ).textContent = total;`としてあげれば記述を少なくできます！

2023-06-23 00:33 UTC, s-iwakawa commented on Day4/task4-2.html
> +      };
補足で、`let chk1_opt = 0`
と宣言しているので、わざわざ`else if (//略) { chk1_opt = 0 }`で0を再代入しなくてもifを通らなければ0のままです。

2023-06-23 01:09 UTC, jwei176 commented on Day4/task4-2.html
> +      };
お疲れ様です。

>これをchkbox[1]の分を用意して、最後に... ).textContent = total;としてあげれば記述を少なくできます！
>補足で、let chk1_opt = 0と宣言しているので、わざわざelse if (//略) { chk1_opt = 0 }で0を再代入しなくてもifを通らなければ0のままです。

上記の部分を修正いたしましたので、こちらからマージさせていただきます！
レビューありがとうございました。🙇‍♂️

2023-06-23 01:09 UTC, merged