Task8
jwei176/kintone_dojo pull request #9
Opened 2023-06-22 05:50 UTC by jwei176

いつもお世話になっております。

task8のRESTAPI課題①を完了しましたので、レビューお願いいたします。
お忙しいところ恐縮ですが、よろしくお願いいたします！🙇‍♂️

2023-06-23 01:49 UTC, s-iwakawa requested changes

2023-06-23 01:49 UTC, s-iwakawa commented on task8.js
> +    const resp = await kintone.api(kintone.api.url('/k/v1/app/form/fields.json', true), 'GET', {'app': 15});
このREST APIは必要ですか？

30行目はないものと仮定して、
9 - 29 行目でテーブルは作れてはいますが、30行目を削除した状態では反映できていませんでした。

同期非同期の観点から 30行目を削除しても動くようにするにはどうすればよいか、再度考えてみてください！

2023-06-23 01:49 UTC, s-iwakawa commented on task8.js
> +      app: '15',
今回のREST APIでデータを取得してくる先のアプリは自分自身、つまり今開いているレコードなので、アプリIDの数字をベタ書きするのはナンセンスです。

より一般化した書き方にするように心がけると良いです。
同じアプリ構成をした別アプリ(別のアプリidをもつ同じアプリ)にこのjsファイルを適応しても編集することなく動くことが理想と言い換えても良い。

2023-06-23 01:49 UTC, s-iwakawa commented on task8.js
> +        list.push(structuredClone(event.record.Table.value[0]));
テーブルの構造を作る際には、kintoneカスタマイズっぽい書き方をする方が好ましいです。どこに何が入っているかわからなくなるため、ブラックボックス化してしまう可能性があります。
そのため、
```
{
  value: {
    Action5: {
      type: 'xxx',
      value: xxx
    }
  }
}
```
のような構造をループ処理で配列に追加する方法が今回は良いと思います。

2023-06-23 06:43 UTC, jwei176 commented
お疲れ様です！

タスク８の修正をしましたので、
ご確認のほどよろしくお願いいたします！🙇‍♂️

2023-06-26 08:12 UTC, s-iwakawa commented on task8.js
`console.log()`はデバッグに使うのはいいのですが、提出ファイルには含ませないようにしましょう！

2023-06-26 08:12 UTC, s-iwakawa commented on task8.js
14, 15 行目のいらないコメントも外しましょう！

2023-06-26 08:12 UTC, s-iwakawa commented on task8.js
全体的にスッキリなってOKです！

console.log() を消したらセルフマージでOKです

2023-06-26 08:37 UTC, jwei176 commented
いつもレビューありがとうございます！

>console.log()はデバッグに使うのはいいのですが、提出ファイルには含ませないようにしましょう！

度々失礼しています。
今度気をつけます！
console.log()を消したので、マージいたします。

2023-06-26 08:57 UTC, merged